# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ac90238095859b9c305f25166b675f0be320a51d82a4d1ae7114aad656b193b85abacadbc424ccb35e1da6208d13d613f9ae0d67842390c8696402da0cb870b

test:
  secret_key_base: bff65dba5d46cc53dee83df2266d3c152c5ba531f2fa746905099c2bed9afb97fa9be2df4c667eef36a3228a36cc6067ad61454063bf6be9135d4ac60b7a1daa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
