# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51c583e0e47cd0e1a61cd953d6e5cadec3cdd74051b54811e6ddb3ab9d379e473098a22d1b391ab900d139051d6c43868b9372f83cec7f463d98ecd45196461b

test:
  secret_key_base: 967bb813a817f210e604fb6bf52d9dd216ba83beafb12b9b3f588397c2c0b1d7cd0b2fd7ddecabbf6bf904304cc071a4c1dd75950fa0d1ce3976287cef3faff2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
