source 'https://rubygems.org'

gem "app", path: "components/app"

#Ensuring correct version of transitive dependency
gem "trueskill", git: "https://github.com/perrym5/trueskill", ref: "a93a3850b967ecbacafa9f3526f9175ddfe0bde8"

gem 'rails', '4.1.9'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'spring', group: :development
