# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5287cd488f525a7727d051c3def73ab3f78d44722be45e3bd039b30f8d3ad58db34d6a3831ce9655578c93001c17a0cbd013ce4c40d7e889ab235be02ad97f42

test:
  secret_key_base: 57dd868f6f176f1ffe647b37658888311bd4490d2bc5ed6f536eba1ad42a8a1aec377a8da66552f3e86ce9a29f6796e6d03535551f700d2fc8b205a8cc337b35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
